"""Independent controlled-event replay for the locked verification set.

The main verifier is fitted from submitted-ledger features and its risk truth
is generated by a different optimization policy.  This module makes that
separation executable: a predeclared event tariff and service floor are applied
to a gate-masked ledger, while the benchmark response is solved by an
independently parameterized policy with no statistical target, risk envelope,
or candidate weights.  The
result is a controlled intervention replay, not a claim about an unobserved
utility dispatch event.
"""

from __future__ import annotations

import json
import logging
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from .baselines import baseline_metrics, response_delivery_metrics, response_metrics
from .experiments import _inputs, _solve_day_with_buffer
from .progress import progress as tqdm


TRUTH_SOURCE = "independent_gate_causal_event_policy"


def _solve_independent_pair(
    arrivals: np.ndarray,
    prices: np.ndarray,
    cfg: dict[str, Any],
    gate: int,
    event_slots: list[int],
    response_price: float,
    baseline_price: float,
    participating_destinations: list[int],
    minimum_participant_event_mwh: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return no-event and event trajectories from a policy not used in fitting."""
    committed = np.asarray(arrivals, dtype=float).copy()
    committed[gate:] = 0.0
    # The independent benchmark has no target profile, learner, risk budget,
    # or candidate hull. It solves the exact release/deadline/capacity LP
    # under two objective functions on the predeclared participating sites.
    baseline = _solve_day_with_buffer(
        committed,
        prices,
        cfg,
        # The independent contract intentionally prepositions flexible work
        # in the event window.  This is an exact strategic-reference LP, not a
        # copy of the verifier's predicted baseline.
        mode="strategic_reference",
        dr_price=float(baseline_price),
        event_probability=1.0,
        projection_weight=0.0,
        participating_destinations=participating_destinations,
        require_all_arrivals_at_terminal=False,
        terminal_completion_index=int(cfg["experiments"].get("decision_time_terminal_completion_index", 95)),
        event_slots_override=event_slots,
    )
    response = _solve_day_with_buffer(
        committed,
        prices,
        cfg,
        mode="event_response",
        dr_price=float(response_price),
        projection_weight=0.0,
        participating_destinations=participating_destinations,
        # This predeclared floor is the structural policy difference from the
        # gate response: it creates an event-bearing meter without importing
        # any verifier target or locked outcome.
        minimum_participant_event_mwh=float(minimum_participant_event_mwh),
        require_all_arrivals_at_terminal=False,
        terminal_completion_index=int(cfg["experiments"].get("decision_time_terminal_completion_index", 95)),
        event_slots_override=event_slots,
    )
    if not baseline.success or not response.success:
        message = baseline.solver_message if not baseline.success else response.solver_message
        raise RuntimeError(f"Independent controlled-event LP failed: {message}")
    return np.asarray(baseline.power_mw, dtype=float), np.asarray(response.power_mw, dtype=float)


def _solve_gate_response(
    arrivals: np.ndarray,
    prices: np.ndarray,
    cfg: dict[str, Any],
    gate: int,
    event_slots: list[int],
    response_price: float,
    baseline_price: float,
    committed_service_mwh: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Solve the deployable one-site gate contract and its response plan."""
    committed = np.asarray(arrivals, dtype=float).copy()
    committed[gate:] = 0.0
    baseline = _solve_day_with_buffer(
        committed,
        prices,
        cfg,
        mode="strategic_reference",
        dr_price=float(baseline_price),
        event_probability=1.0,
        projection_weight=0.0,
        participating_destinations=list(cfg["market"].get("participating_data_center_indices", [0])),
        minimum_participant_event_mwh=float(committed_service_mwh),
        require_all_arrivals_at_terminal=False,
        terminal_completion_index=int(cfg["experiments"].get("decision_time_terminal_completion_index", 95)),
        event_slots_override=event_slots,
    )
    if not baseline.success:
        raise RuntimeError(f"Gate baseline LP failed: {baseline.solver_message}")
    upper = np.full_like(
        baseline.power_mw,
        float(cfg["project"]["fixed_facility_load_mw"])
        + float(cfg["project"]["flexible_capacity_mw"]),
    )
    upper[:, event_slots] = np.minimum(upper[:, event_slots], baseline.power_mw[:, event_slots])
    response = _solve_day_with_buffer(
        committed,
        prices,
        cfg,
        mode="event_response",
        dr_price=float(response_price),
        projection_weight=0.0,
        participating_destinations=list(cfg["market"].get("participating_data_center_indices", [0])),
        power_upper_mw=upper,
        require_all_arrivals_at_terminal=False,
        terminal_completion_index=int(cfg["experiments"].get("decision_time_terminal_completion_index", 95)),
        event_slots_override=event_slots,
    )
    if not response.success:
        raise RuntimeError(f"Gate response LP failed: {response.solver_message}")
    return np.asarray(baseline.power_mw, dtype=float), np.asarray(response.power_mw, dtype=float)


def run_exp23_independent_event_replay(
    root: Path,
    cfg: dict[str, Any],
    logger: logging.Logger,
) -> None:
    """Evaluate the verifier and gate contract against an independent policy."""
    folder = root / "experiments/exp23_independent_event_replay"
    final = folder / "results/final"
    figures = folder / "figures"
    final.mkdir(parents=True, exist_ok=True)
    figures.mkdir(parents=True, exist_ok=True)
    profile_path = root / "experiments/exp2_baseline_verification/results/intermediate/test_profiles.npz"
    if not profile_path.exists():
        raise FileNotFoundError(f"Experiment-2 profiles are missing: {profile_path}")
    stored = np.load(profile_path, allow_pickle=False)
    days = stored["days"].astype(int)
    methods = [str(value) for value in stored["methods"].tolist()]
    risk_index = methods.index("Risk-Constrained Convex Verifier")
    risk_profiles = np.asarray(stored["baselines"][:, risk_index], dtype=float)
    arrivals_days, _, _, _, _, prices, _ = _inputs(root, cfg, logger)
    event_slots = list(map(int, cfg["market"]["event_slots"]))
    gate = int(cfg["experiments"].get("decision_time_event_gate_slot", min(event_slots)))
    response_price = float(cfg["experiments"].get("independent_event_response_price_per_mwh", 150.0))
    gate_price = float(cfg["experiments"].get("decision_time_response_dr_prices", [10.0])[-1])
    baseline_price = float(cfg["experiments"].get("independent_event_baseline_price_per_mwh", 120.0))
    independent_participants = [
        int(value)
        for value in cfg["experiments"].get(
            "independent_event_participating_data_center_indices",
            cfg["market"].get("participating_data_center_indices", [0]),
        )
    ]
    independent_minimum_service = float(
        cfg["experiments"].get("independent_event_minimum_service_mwh", 0.0)
    )
    if not independent_participants:
        raise ValueError("independent event policy requires at least one participating site")
    if any(value < 0 or value >= prices.shape[0] for value in independent_participants):
        raise ValueError("independent event policy contains an invalid participating site")
    if independent_minimum_service < 0.0:
        raise ValueError("independent event service floor must be nonnegative")
    gate_baseline_price = float(
        cfg["experiments"].get("independent_gate_baseline_price_per_mwh", 120.0)
    )
    gate_participants = [
        int(value)
        for value in cfg["market"].get("participating_data_center_indices", [0])
    ]
    committed_service = float(
        cfg["experiments"].get("decision_time_committed_event_service_mwh", 0.0)
    )
    if np.isclose(response_price, gate_price) and np.isclose(
        baseline_price, gate_baseline_price
    ):
        raise ValueError(
            "The independent controlled-event tariff pair must differ from the gate tariff pair"
        )
    if independent_participants == gate_participants and np.isclose(
        independent_minimum_service, committed_service
    ):
        raise ValueError(
            "The independent controlled-event participant set or service floor must differ from the gate contract"
        )
    if gate < 0 or gate >= min(event_slots):
        raise ValueError("The independent event replay requires a gate before the event")

    workers = int(cfg["experiments"].get("independent_event_workers", 4))
    if not 1 <= workers <= 20:
        raise ValueError("independent_event_workers must be between 1 and 20")

    tasks = [(int(local), int(day)) for local, day in enumerate(days)]

    def solve_one(task: tuple[int, int]) -> dict[str, Any]:
        local, day = task
        independent_baseline, independent_response = _solve_independent_pair(
            arrivals_days[day],
            prices,
            cfg,
            gate,
            event_slots,
            response_price,
            baseline_price,
            independent_participants,
            independent_minimum_service,
        )
        gate_baseline, gate_response = _solve_gate_response(
            arrivals_days[day], prices, cfg, gate, event_slots, gate_price, gate_baseline_price, committed_service
        )
        # The independent policy supplies the locked event meter.  The
        # verifier's profile is evaluated without using that meter in fitting.
        risk_delivery = response_metrics(
            risk_profiles[local],
            independent_baseline,
            independent_response,
            event_slots,
            float(cfg["project"]["interval_minutes"]) / 60.0,
        )
        gate_delivery = response_delivery_metrics(
            gate_baseline,
            gate_response,
            independent_baseline,
            independent_response,
            event_slots,
            float(cfg["project"]["interval_minutes"]) / 60.0,
        )
        gate_error = baseline_metrics(gate_baseline, independent_baseline, event_slots)
        risk_error = baseline_metrics(risk_profiles[local], independent_baseline, event_slots)
        return {
            "local": local,
            "day": day,
            "independent_baseline": independent_baseline,
            "independent_response": independent_response,
            "gate_baseline": gate_baseline,
            "gate_response": gate_response,
            "risk_delivery": risk_delivery,
            "gate_delivery": gate_delivery,
            "gate_error": gate_error,
            "risk_error": risk_error,
        }

    rows: list[dict[str, Any]] = []
    profile_rows: list[dict[str, Any]] = []
    logger.info("Experiment 23 independent event replay: %d days, %d workers", len(tasks), workers)
    progress = tqdm(total=len(tasks), desc="Exp23 independent event replay")
    with ThreadPoolExecutor(max_workers=workers) as executor:
        for result in executor.map(solve_one, tasks):
            for label, metrics, error in (
                ("Risk-Constrained Convex Verifier", result["risk_delivery"], result["risk_error"]),
                ("Gate-committed response", result["gate_delivery"], result["gate_error"]),
            ):
                rows.append(
                    {
                        "day": result["day"],
                        "method": label,
                        "truth_source": TRUTH_SOURCE,
                        "event_intervention": True,
                        **error,
                        **metrics,
                    }
                )
            profile_rows.append(
                {
                    "day": result["day"],
                    "independent_baseline": result["independent_baseline"],
                    "independent_response": result["independent_response"],
                    "gate_baseline": result["gate_baseline"],
                    "gate_response": result["gate_response"],
                }
            )
            progress.update(1)
    progress.close()

    daily = pd.DataFrame(rows).sort_values(["day", "method"]).reset_index(drop=True)
    daily.to_csv(final / "independent_event_replay_daily.csv", index=False)
    summary = (
        daily.groupby("method", as_index=False)
        .agg(
            locked_days=("day", "nunique"),
            nrmse=("nrmse", "mean"),
            false_response_mwh=("false_response_mwh", "mean"),
            payable_response_mwh=("meter_capped_response_mwh", "mean"),
            underpayment_mwh=("meter_capped_underpayment_mwh", "mean"),
            credit_precision=("credit_precision", "mean"),
            credit_recall=("credit_recall", "mean"),
            credit_f1=("credit_f1", "mean"),
            response_tracking_mae_mw=("response_tracking_mae_mw", "mean"),
        )
    )
    summary.to_csv(final / "independent_event_replay_summary.csv", index=False)

    # A compact profile archive keeps the controlled intervention reproducible
    # without reintroducing the incomplete full-ledger NPZ into version control.
    profile_rows = sorted(profile_rows, key=lambda item: item["day"])
    response_differences = [
        np.abs(row["independent_response"] - row["gate_response"])
        for row in profile_rows
    ]
    baseline_differences = [
        np.abs(row["independent_baseline"] - row["gate_baseline"])
        for row in profile_rows
    ]
    maximum_response_difference = float(
        max((float(np.max(value)) for value in response_differences), default=0.0)
    )
    mean_response_difference = float(
        np.mean([float(np.mean(value[:, event_slots])) for value in response_differences])
        if response_differences
        else 0.0
    )
    maximum_baseline_difference = float(
        max((float(np.max(value)) for value in baseline_differences), default=0.0)
    )
    mean_baseline_difference = float(
        np.mean([float(np.mean(value[:, event_slots])) for value in baseline_differences])
        if baseline_differences
        else 0.0
    )
    if maximum_response_difference <= 1e-8:
        raise RuntimeError(
            "The independent event policy collapsed to the gate response; "
            "the controlled replay must retain a predeclared structural difference"
        )
    if maximum_baseline_difference <= 1e-8:
        raise RuntimeError(
            "The independent event policy collapsed to the gate baseline; "
            "the baseline objective and participant set must remain distinct"
        )
    np.savez_compressed(
        final / "independent_event_profiles.npz",
        days=np.asarray([row["day"] for row in profile_rows], dtype=int),
        independent_baseline=np.asarray([row["independent_baseline"] for row in profile_rows]),
        independent_response=np.asarray([row["independent_response"] for row in profile_rows]),
        gate_baseline=np.asarray([row["gate_baseline"] for row in profile_rows]),
        gate_response=np.asarray([row["gate_response"] for row in profile_rows]),
    )

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plot = summary.sort_values("nrmse").reset_index(drop=True)
    fig, ax = plt.subplots(figsize=(7.1, 3.8), constrained_layout=True)
    y = np.arange(len(plot))
    ax.barh(y, plot["credit_f1"], color=["#0072B2", "#D55E00"][: len(plot)])
    ax.set_yticks(y, plot["method"], fontsize=8.5)
    ax.set_xlabel("Credit F1 against independent event meter")
    ax.set_title("Controlled event replay on the locked gate information set")
    ax.grid(axis="x", alpha=0.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    for suffix in ("png", "pdf"):
        fig.savefig(figures / f"fig26_independent_event_replay.{suffix}", dpi=320, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    metadata = {
        "experiment": "independent controlled-event replay",
        "locked_days": int(len(days)),
        "event_gate_slot": gate,
        "event_slots": event_slots,
        "truth_source": TRUTH_SOURCE,
        "event_intervention": True,
        "causal_intervention_claim": False,
        "identification_statement": (
            "A predeclared tariff shock and service floor are applied to the gate-masked "
            "submitted ledger. The independently parameterized policy has no statistical "
            "target, risk envelope, candidate weights, or verifier output as an input. This is a controlled "
            "optimization replay, not a field utility-event estimate."
        ),
        "independent_policy": {
            "objective": (
                "exact release/deadline/capacity LP with a distinct event tariff "
                "and a predeclared event-service floor on the participating site set"
            ),
            "response_price_per_mwh": response_price,
            "baseline_price_per_mwh": baseline_price,
            "participating_data_center_indices": independent_participants,
            "minimum_participant_event_mwh": independent_minimum_service,
            "tariff_pair_distinct_from_gate": True,
            "participant_set_distinct_from_gate": independent_participants != gate_participants,
            "structurally_distinct_from_gate": True,
            "policy_family": "exact release/deadline LP with independent tariff and participant set",
            "maximum_response_difference_from_gate_mw": maximum_response_difference,
            "mean_event_response_difference_from_gate_mw": mean_response_difference,
            "maximum_baseline_difference_from_gate_mw": maximum_baseline_difference,
            "mean_event_baseline_difference_from_gate_mw": mean_baseline_difference,
            "post_gate_arrivals_used": False,
            "future_arrivals_used_for_decision": False,
            "risk_oracle_reused": False,
        },
        "gate_policy": {
            "objective": "same exact LP with the selected gate tariff and committed service constraint",
            "response_price_per_mwh": gate_price,
            "baseline_price_per_mwh": gate_baseline_price,
            "committed_event_service_mwh": committed_service,
            "post_gate_arrivals_used": False,
        },
        "workers": workers,
        "daily_file": "independent_event_replay_daily.csv",
        "summary_file": "independent_event_replay_summary.csv",
        "profiles_file": "independent_event_profiles.npz",
        "figure": "fig26_independent_event_replay.pdf",
    }
    (final / "experiment_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    logger.info("Experiment 23 complete: %d independent event days", len(days))
